# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "admin", first_name: "Harmonic", last_name: "Admin", email: "harmonicgardensad@gmail.com", role: "Admin", hourly_rate: "1", password: "password", phone_number: "2032735191");
User.create(username: "xtbxadmin", first_name: "Super", last_name: "Admin", email: "barnes.thomas.c@gmail.com", role: "Admin", hourly_rate:"1", password:"password", phone_number:"2035640219");
					
Client.create(first_name: "Adam", last_name:"Milakofsky", email: "amilakofsky@gmail.com", address: "1 Spring Rd, Cos Cob CT");
Client.create(first_name: "Aditi", last_name:"Davray", home_phone: "6178408831", email:"aditidavray@gmail.com", address:"174 Cognewaugh");
Client.create(first_name: "Aditis", last_name:"Neighbor", address:"-");
Client.create(first_name: "Aida", last_name:"Bevis", email:"aidabevis@outlook.com", address:"178 Weaver St, Greenwich CT");
Client.create(first_name: "Anthony", last_name:"Narvaez", home_phone: "9149796047", address: "143 Woodside Dr, Greenwich CT");
Client.create(first_name: "Art", last_name: "Auch", home_phone:"2033215181", email: "artauch@aol.com", address:"19 Old Kings Highway");
Client.create(first_name: "Audrey", last_name:"Lederman", email:"audinog@aol.com", address: "Sound Beach Ave");
Client.create(first_name: "Audubon", last_name:"CT", email: "smartin@audubon.org", address: "-");
Client.create(first_name: "Bojadzic Construction", last_name:"LLC", home_phone: "2032231915", email: "bmasonry@gmail.com", address:"-");
Client.create(first_name: "Brenn", last_name:"Jain", home_phone:"2033996749", email:"brennjain@yahoo.com", address:"46 Highmeadow Rd, Old Greenwich CT");
Client.create(first_name: "Brian", last_name:"-", address: "22 Turner Drive, Greenwich CT 06831");
Client.create(first_name: "Carissa", last_name:"Fallan", home_phone:"3609124789", email:"carissa.fallan@gmail.com", address: "13 Linwood Ave, Riverside CT 06878");
Client.create(first_name: "Carol", last_name:"Wasserman", email: "carol.wasserman@gmail.com", address:"-");
Client.create(first_name: "Caroline", last_name:"A.", email: "Caroline.auw@pepsico.com", address: "3 Bennett Rd");
Client.create(first_name: "Chris", last_name:"Allred", email: "chrisjallred@gmail.com", address:"-");
Client.create(first_name: "Christienne", last_name:"Genaro", email:"christienne.genaro@gmail.com", address:"30 Willets Rd, Mt Kisco NY 10549");
Client.create(first_name: "Craig", last_name:"Berendowski", home_phone: "8145713074", email:"craig.berendo@gmail.com", address: "1 Grant Ave, Old Greenwich");
Client.create(first_name: "D5", last_name: "LLC", email: "kdilascia@optonline.net", address:"11 Connecticut Ave");
Client.create(first_name: "Dan", last_name:"Connell", home_phone:"2023655940", email: "Daniel.h.connell@gmail.com", address:"7 Wescott Ct, Riverside CT");
Client.create(first_name: "Dawn", last_name:"Bezviner", email:"dawnbez@att.net", address:"343 Westover Rd, Stamford, CT 06902");
Client.create(first_name: "Debbie", last_name:"Mullin", email:"dmullin47@aol.com", address:"82 Honey Hollow Rd, Pound Ridge NY");
Client.create(first_name: "Dorothy", last_name:"Cardillo", email:"dorothy.cardillo@td.com", address:"31 Lancer Rd, Riverside CT 06878");
Client.create(first_name: "Dr. & Mrs.", last_name:"Connors", email: "rcconnors@aol.com", address:"15 Orchard Drive, Cos Cob CT");
Client.create(first_name: "Ed", last_name:"Waesche", email: "ewvast@gmail.com", address: "-");
Client.create(first_name: "Edward", last_name:"Martino", home_phone: "9082553297", email:"edmartino2@gmail.com", address:"3 Carriage Road, Cos Cob CT 06807");
Client.create(first_name: "Eric & Hillary", last_name:"Messer", email:"eric@sunrisebuilding.com", address:"-");
Client.create(first_name: "Ernst", last_name:"Schaumburg", cell_phone:"3129277145", email: "ernstsonline@gmail.com", address: "35 Shore Road, Old Greenwich CT 06870");
Client.create(first_name: "Flo", last_name:"Strauss", home_phone: "2039403376", email:"flostrauss@optonline.net", address:"1 North Street, Old Greenwich CT");
Client.create(first_name: "Ginny", last_name:"Waters", email:"ginnywaters@me.com", address:"52 Frontier Rd, Cos Cob CT 06807");
Client.create(first_name: "Glen", last_name:"Clark", email:"plazag15@yahoo.com", address:"29 Maryanne Ln, Stamford");
Client.create(first_name: "Greg", last_name:"Durkin", home_phone: "2033882297", email:"gdurkin@sof328.com", address:"424 Ocean Drive West, Stamford CT 06902");
Client.create(first_name: "Hannah", last_name:"Granade", email:"hannahcgranade@gmail.com", address:"11 Angus Lane");
Client.create(first_name: "Hannah", last_name:"Pasterczyk", cell_phone:"5085771315", email:"hpasterc@gmail.com", address:"Sinawoy Road, Cos Cob CT 06807");
Client.create(first_name: "Harumi & Bob", last_name:"Stewart", home_phone: "2033441404", cell_phone: "2032495668", email: "harumi.stewart@cbmoves.com", address:"50 Highmeadow Rd, Old Greenwich CT 06870");
Client.create(first_name: "Heather", last_name:"Woodworth", email:"hkw3k@virginia.edu", address:"-");
Client.create(first_name: "Inna", last_name:"Gittleman", email: "innapa2008@gmail.com", address:"-");
Client.create(first_name: "Isaac", last_name:"-", email:"isaacklesh@hotmail.com");
Client.create(first_name: "Jacob", last_name:"Steinberg", email:"Jacob.r.steinberg@gmail.com", address:"-");
Client.create(first_name: "Jane", last_name:"Balter", email:"jdbalter@verizon.net", address:"5 Willetts Rd, Mt Kisco NY 10549");
Client.create(first_name: "Jarrod", last_name:"Kaplan", email:"jarrod.kaplan@gmail.com", address:"238 Stanwich Rd, Greenwich, CT");
Client.create(first_name: "Jason & Kuka", last_name:"Sutherland", email: "jrsutherland@yahoo.com", address:"227 Riverside Ave, Riverside CT");
Client.create(first_name: "Jeanine", last_name: "Jackson", home_phone: "2038564713", email:"peoplescapes@aol.com", address:"3 Wescott Ct");
Client.create(first_name: "Jenny", last_name:"Friedman", cell_phone: "4405227348", email:"jacsontos@gmail.com", address: "220 Byram Shore Rd, Greenwich CT");
Client.create(first_name: "Jenny Y.", last_name:"Lee", email:"jenny.y.lee@jpmorgan.com", address:"-");
Client.create(first_name: "John", last_name:"Regan", email:"jpreganesq@aol.com", address:"124 Lancer Rd");
Client.create(first_name: "Julie", last_name:"-", email: "juliezjules@gmail.com", address:"-");
Client.create(first_name: "Kaitlin", last_name:"Holt", home_phone: "9178835784", email:"kaitlin.h.holt@gmail.com", address:"60 Park Ave, Old Greenwich, CT");
Client.create(first_name: "Kathy", last_name:"Stewart", home_phone: "2035366797", cell_phone:"2035366797", email:"kstewart.ssns.director@gmail.com", address:"44 Benjamin Street, Old Greenwich CT 06870");
Client.create(first_name: "Katie", last_name:"DiLascia", home_phone:"2033215371", email:"kdilascia@optonline.net", address:"-");
Client.create(first_name: "Katie", last_name:"Jackson", email: "kt8011@gmail.com", address:"40 Lockwood Ave, Old Greenwich CT");
Client.create(first_name: "Katja", last_name:"-", email:"kpita@me.com", address:"3 Grant Ave");
Client.create(first_name: "Kevin", last_name:"Foley", home_phone: "6467251599", email:"kevin.x.foley@gmail.com", address:"116 Lockwood Rd");
Client.create(first_name: "L", last_name: "Lancetti", email: "sl.lancetti@yahoo.com", address:"70 North Street, Greenwich, CT 06830");
Client.create(first_name: "Larry", last_name:"Perrone", email:"larry.perrone@gmail.com", address:"31 Church St West, Greenwich, CT 06830");
Client.create(first_name: "Laura", last_name:"Meyers", email: "laurameyer3@gmail.com", home_phone: "9145520183", address:"-");
Client.create(first_name: "Living", last_name:"Arrangements", email: "chriswuest1989@gmail.com", address:"-");
Client.create(first_name: "Luis", last_name:"Di Como", email:"luis.di-como@unilever.com", address:"5 Cat Rock Rd, Greenwich");
Client.create(first_name: "Marcy", last_name:"Abbot", cell_phone: "2032534404", address: "170 Overlook Dr, Greenwich CT 06830");
Client.create(first_name: "Marija", last_name: "Mikolajczak", email:"marijamikolajczak@gmail.com", address:"-");
Client.create(first_name: "Marina", last_name:"Shrady", email:"shradymarina@gmail.com", address:"-");
Client.create(first_name: "Mark", last_name:"-", address:"114 Pemberwick Rd, Greenwich CT");
Client.create(first_name: "Mary Ellen", last_name: "Munro", email:"memunro2@gmail.com", address:"15 Amherst Rd, Riverside CT", home_phone:"2032499629");
Client.create(first_name: "Mat.", last_name:"Friedman", address:"-");
Client.create(first_name: "Maureen", last_name:"Sheehan", email:"maureen.elizabeth.sheehan@gmail.com", address:"-");
Client.create(first_name: "Maxim", last_name:"Borbat", email: "maxim.borbat@gmail.com", address:"181 Cognewaugh Rd");
Client.create(first_name: "Mey", last_name: "Marple", home_phone:"9144205983", email:"marplegirl@me.com", address:"100 Byram Lake Rd, Mt Kisco NY 10549");
Client.create(first_name: "Mike", last_name:"Ettinger", email: "mike_ettinger@hotmail.com", address:"-");
Client.create(first_name: "Mikhail", last_name:"Levakin", cell_phone:"6463186197", email:"mikhail.levakin@gmail.com", address:"27 Fado Ln, Cos Cob CT 06807");
Client.create(first_name: "Mrs.", last_name:"Allred", address:"-");
Client.create(first_name: "Deni", last_name:"Carter", address:"-", email:"Denicarter@aol.com");
Client.create(first_name: "Ms.", last_name:"Mahoney", email:"foofie30@aol.com", address:"364 Valley Rd, Cos Cob CT");
Client.create(first_name: "Olga", last_name:"Gottlieb", email: "historikorders@gmail.com", address:"127 Stanwich Rd, Greenwich, CT 06830");
Client.create(first_name: "Pam", last_name:"Olney", cell_phone: "2032735148", email:"olneyp@optonline.net", address:"-");
Client.create(first_name: "Patricia", last_name:"DeLuca", home_phone: "2033260175", email:"eltonjohn01@aol.com");
Client.create(first_name: "Patty", last_name:"Burke", home_phone: "2034850085", cell_phone: "2035705805", email: "patty15@optonline.net", address:"-");
Client.create(first_name: "Pebbles Knoll Conso", last_name:"Association",email:"aalatsas@optonline.net", address:"-");
Client.create(first_name: "Peggy", last_name:"Grifferty", address:"-");
Client.create(first_name: "Peter", last_name: "Polidoro", home_phone: "2032497953", address:"-");
Client.create(first_name: "Phil", last_name:"Lochner", address:"-");
Client.create(first_name: "Rafaela", last_name:"Franca", email:"rafaela.rein@gmail.com", address:"Long View Ave, Riverside CT");
Client.create(first_name: "Rebecca & Marshall", last_name:"Cooper", address:"-");
Client.create(first_name: "Rebecca", last_name:"Carey", home_phone: "2032539897", email:"Rccarey@optonline.net", address:"3 Shore Acre Rd, Old Greenwich CT 06878");
Client.create(first_name: "Regan", last_name:"Gilbride", email:"regan.gilbride@gmail.com", address:"31 Sound Beach Ave, Old Greenwich");
Client.create(first_name: "Rimmie", last_name:"Mosely", email: "rimmiemosley@aol.com", address:"-");
Client.create(first_name: "RJ", last_name:"Becker", home_phone: "9143562020", email:"rjbeckerii@yahoo.com", address:"52 Butler St, Cos Cob");
Client.create(first_name: "Saleem", last_name:"Begg", email:"Saleembegg@usa.net", address:"-");
Client.create(first_name: "Sergio", last_name:"-", home_phone: "2034343929", email:"maza081976@gmail.com", address:"55 Orchard Drive, Greenwich CT 06830");
Client.create(first_name: "Sharon", last_name: "Sunoo", email: "sunoo@optonline.net", address:"7 Hendrie Drive, Old Greenwich CT 06870");
Client.create(first_name: "Shelly", last_name: "Shah", address:"3 Hearthstone Drive");
Client.create(first_name: "Sonia", last_name:"Kandhari", email: "soniakaur@gmail.com", address:"7 Juniper Ln, Riverside, CT");
Client.create(first_name: "Sophia", last_name:"Brosterman", email:"sophia.brosterman@gmail.com", address:"39 Angus Lane");
Client.create(first_name: "Susan", last_name:"-", email:"Svpiscopo@gmail.com", address:"8 Salem");
Client.create(first_name: "Susan", last_name:"Boolbol", cell_phone: "9178814686", email:"emken2004@gmail.com", address:"-");
Client.create(first_name: "Suzanne", last_name:"Roth", home_phone: "5864531799", email:"sehroth@gmail.com", address:"9 Manor Rd");
Client.create(first_name: "Sweet", last_name:"Pea's", email: "rfpita@sweetpeasct.com", address:"212 Sound Beach Ave, Old Greenwich");
Client.create(first_name: "Vanya", last_name:"Todorovic", email:"vanya_todorovic@hotmail.com", address:"36 Starin Dr, Stamford CT");
Client.create(first_name: "Vincent", last_name:"Carey", email:"Vinny.carey@itt.com", address:"-");
Client.create(first_name: "Whitney", last_name:"-", cell_phone:"2038489849", email:"ctgoodlife17@gmail.com");
Client.create(first_name: "Yinlei", last_name:"Yu", email:"yinlei@gmail.com", address:"9 Wilmot Lane Riverside CT");
Client.create(first_name: "Young", last_name:"-", email: "young1231@gmail.com", address:"12 Orchard Rd");